version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demand-forecasting-frontend
    ports:
      - "6600:6600"
    environment:
      # Backend service URLs (pointing to backend compose)
      - VITE_AUTH_URL=http://localhost:6601
      - VITE_DATA_URL=http://localhost:6603
      - VITE_DIM_URL=http://localhost:6604
      - VITE_INGEST_URL=http://localhost:6602
      - VITE_DATA_API_KEY=sf_4e77abfe2e799431a21a9bf586f2a67fb518910e2f1b50c346b3b80fb9bdf5ca
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6600"]
      interval: 30s
      timeout: 10s
      retries: 3
